import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/core/Sidebar";
import Header from "@/components/ui/core/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex relative h-screen    ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidebar />
        <div className="flex-1 flex flex-col overflow-hidden ">
          <Header />
          <main className="flex-1 overflow-y-auto p-5 bg-gray-100">
            <div className="min-h-[calc(100vh-100px)]">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
